Add key pair change tests to E2E.Test
couger-inc/cream pull request #109
Opened 2021-11-18 06:36 UTC by exfinen

- Refactor existing E2E.Test code to reuse for the new tests
- Remove unused code and variables in E2E.Test
- Add test cases for key pari changes to E2E.Test

2021-11-18 12:31 UTC, kazuakiishiguro commented on packages/contracts/test/E2E.Test.ts
> +                // coordintor transfer tokens voted to recipient currently owned by cream to recipient
@exfinen 
typo: coordintor->coordinator

2021-11-18 12:32 UTC, kazuakiishiguro commented
Found a minor typo at https://github.com/couger-inc/cream/pull/109/files#r752195863

2021-11-18 12:32 UTC, kazuakiishiguro requested changes
Found a minor typo at https://github.com/couger-inc/cream/pull/109/files#r752195863

2021-11-18 13:14 UTC, exfinen commented on packages/contracts/test/E2E.Test.ts
> +                // coordintor transfer tokens voted to recipient currently owned by cream to recipient
no objection!

2021-11-18 13:21 UTC, exfinen commented on packages/contracts/test/E2E.Test.ts
> +                // coordintor transfer tokens voted to recipient currently owned by cream to recipient
fixed

2021-11-19 01:00 UTC, kazuakiishiguro approved these changes

2021-11-19 01:00 UTC, merged